name: Weekday Slack Reminder

on:
  schedule:
    # 한국 시간 09:55 = UTC 00:55. (1-5는 월~금요일을 의미합니다)
    - cron: '55 0 * * 1-5'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install slack_sdk
      - run: python send_reminder.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
